// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DisableAutostart() {
  return window['go']['main']['App']['DisableAutostart']();
}

export function EnableAutostart() {
  return window['go']['main']['App']['EnableAutostart']();
}

export function GetDatesWithTasks() {
  return window['go']['main']['App']['GetDatesWithTasks']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTasksForDate(arg1) {
  return window['go']['main']['App']['GetTasksForDate'](arg1);
}

export function GetTodayTasks() {
  return window['go']['main']['App']['GetTodayTasks']();
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function ResetWindowPosition() {
  return window['go']['main']['App']['ResetWindowPosition']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowPosition() {
  return window['go']['main']['App']['SaveWindowPosition']();
}

export function ToggleDone(arg1) {
  return window['go']['main']['App']['ToggleDone'](arg1);
}

export function ToggleExpanded() {
  return window['go']['main']['App']['ToggleExpanded']();
}

export function UpdateText(arg1, arg2) {
  return window['go']['main']['App']['UpdateText'](arg1, arg2);
}
