// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:string,arg2:string):Promise<models.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function DisableAutostart():Promise<void>;

export function EnableAutostart():Promise<void>;

export function GetDatesWithTasks():Promise<Array<string>>;

export function GetSettings():Promise<models.Settings>;

export function GetTaskCountsByDate():Promise<Record<string, number>>;

export function GetTasksForDate(arg1:string):Promise<Array<models.Task>>;

export function GetTodayTasks():Promise<Array<models.Task>>;

export function IsAutostartEnabled():Promise<boolean>;

export function IsExpanded():Promise<boolean>;

export function ReorderTasks(arg1:Array<string>):Promise<void>;

export function ResetWindowPosition():Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SaveWindowPosition():Promise<void>;

export function ToggleDone(arg1:string):Promise<models.Task>;

export function ToggleExpanded():Promise<void>;

export function UpdateText(arg1:string,arg2:string):Promise<models.Task>;
